name: Discord Bot Runner

on:
  push:
    branches: [ "main" ] # Kodları 'main' dalına yüklediğinde çalışır
  workflow_dispatch: # GitHub sitesinden botu elle başlatmanı sağlar

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Çek
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Bağımlılıkları Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Botu Başlat
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: python bot.py
