name: Send Discord Commit Notification

on:
  push:
    branches: [ "*" ] # Hangi dala push atılırsa atılsın çalışır
  workflow_dispatch: # İstersen GitHub'dan elinle de tetikleyebilirsin

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Botu Çalıştır ve Bildirimi Gönder
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: node index.js
